spring:
  application:
    # 设置当前项目的名称,这个名字会提交给Nacos作为当前微服务项目的名称
    name: nacos-order
  cloud:
    nacos:
      discovery:
        # 配置Nacos的位置,用于提交当前项目信息
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos//localhost:8848
    check: false

seata:
  tx-service-group: csmall_group
  service:
    vgroup-mapping:
      csmall_group: default
  grouplist:
    default: localhost:8091

